
export const services = [
  {
    id: 1,
    name: "Limpeza de Pele Profunda",
    category: "Tratamento Facial",
    company: "Clínica DermaBem",
    professional: "Dra. Ana Silva",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881",
    rating: 4.8,
    reviews: 87,
    price: "R$180",
    duration: "60 min",
    availability: "Hoje",
    company_id: "clinica-dermabem-123",
    professional_id: "dra-ana-silva-456",
    description: "Limpeza de pele completa com extração de cravos e espinhas, esfoliação e hidratação profunda para todos os tipos de pele.",
  },
  {
    id: 2,
    name: "Quiropraxia",
    category: "Fisioterapia",
    company: "FisioSaúde",
    professional: "Dr. Carlos Mendes",
    image: "https://images.unsplash.com/photo-1552693673-1bf958298935",
    rating: 4.9,
    reviews: 112,
    price: "R$150",
    duration: "45 min",
    availability: "Amanhã",
    company_id: "fisiosaude-789",
    professional_id: "dr-carlos-mendes-101",
    description: "Tratamento quiroprático para alinhamento da coluna, alívio de tensões musculares e melhora da postura corporal.",
  },
  {
    id: 3,
    name: "Corte e Hidratação",
    category: "Cabelo",
    company: "Bella Hair Studio",
    professional: "Julia Ferreira",
    image: "https://images.unsplash.com/photo-1560869713-7d0a29430803",
    rating: 4.7,
    reviews: 95,
    price: "R$120",
    duration: "90 min",
    availability: "Hoje",
    company_id: "bella-hair-studio-112",
    professional_id: "julia-ferreira-131",
    description: "Corte personalizado seguido de tratamento de hidratação profunda com produtos profissionais para todos os tipos de cabelo.",
  },
  {
    id: 4,
    name: "Treinamento Funcional",
    category: "Fitness",
    company: "Fit Performance",
    professional: "Ricardo Almeida",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
    rating: 4.6,
    reviews: 64,
    price: "R$90",
    duration: "60 min",
    availability: "3 dias",
    company_id: "fit-performance-141",
    professional_id: "ricardo-almeida-151",
    description: "Sessão de treinamento funcional personalizado com foco em fortalecimento muscular, equilíbrio e condicionamento físico.",
  },
  {
    id: 5,
    name: "Consulta Nutricional",
    category: "Nutrição",
    company: "NutriVida",
    professional: "Dra. Beatriz Costa",
    image: "https://images.unsplash.com/photo-1490818387583-1baba5e638af",
    rating: 4.8,
    reviews: 53,
    price: "R$200",
    duration: "60 min",
    availability: "2 dias",
    company_id: "nutrivida-161",
    professional_id: "dra-beatriz-costa-171",
    description: "Avaliação completa do perfil nutricional com elaboração de plano alimentar personalizado conforme objetivos e necessidades individuais.",
  },
  {
    id: 6,
    name: "Clareamento Dental",
    category: "Odontologia",
    company: "OdontoExcelência",
    professional: "Dr. Marcos Oliveira",
    image: "https://images.unsplash.com/photo-1606811971618-4486d14f3f99",
    rating: 4.9,
    reviews: 78,
    price: "R$450",
    duration: "120 min",
    availability: "Hoje",
    company_id: "odontoexcelencia-181",
    professional_id: "dr-marcos-oliveira-191",
    description: "Procedimento de clareamento dental profissional com gel de alta concentração e luz LED para resultados imediatos e duradouros.",
  }
];

export const specialties = [
  "Todas especialidades",
  "Clínica Dermatológica",
  "Centro de Fisioterapia",
  "Salão de Beleza",
  "Academia e Personal Training",
  "Consultório Nutricional",
  "Clínica Odontológica",
  "Consultório Psicológico",
  "Centro de Massagem",
  "Estúdio de Manicure",
];

export const availabilityOptions = [
  "Qualquer data",
  "Hoje",
  "Amanhã",
  "Esta semana",
  "Próxima semana",
];
